### ISSUE TITLE
Repo tag doesn't match configured format, breaks PCT

### ISSUE THREAD

**Issue by timja** [jenkinsci/commons-lang3-api-plugin#12]
Hi

As seen in https://github.com/jenkinsci/bom/pull/1228#pullrequestreview-1019347740, this repo can't be checked out in PCT

It's because the only tag in this repo is:
```
commons-lang3-api-plugin-v3.12.0.0
```

whereas it's expected to be:
```
commons-lang3-api-3.12.0.0
```

Did you manually change it during release? cc @nhojpatrick

(For now I'll just manually tag a duplicate tag to match what's PCT is expecting to unblock)

https://github.com/jenkinsci/commons-lang3-api-plugin/releases/tag/commons-lang3-api-3.12.0.0

**Comment by jglick** [comment]
> Did you manually change it during release?

Consider https://www.jenkins.io/doc/developer/publishing/releasing-cd/

**Comment by jglick** [comment]
https://github.com/jenkinsci/commons-lang3-api-plugin/tags has both? https://github.com/jenkinsci/commons-lang3-api-plugin/commit/6c800683a3e580d44236b790de7261857abdc0f3 suggests that you are not using the standard

```bash
mvn release:prepare release:perform
```

**Comment by timja** [comment]
> [jenkinsci/commons-lang3-api-plugin/tags](https://github.com/jenkinsci/commons-lang3-api-plugin/tags) has both? [6c80068](https://github.com/jenkinsci/commons-lang3-api-plugin/commit/6c800683a3e580d44236b790de7261857abdc0f3) suggests that you are not using the standard
> 
> ```shell
> mvn release:prepare release:perform
> ```

I manually created the one that was expected by maven to unblock some JCasC changes.

**Comment by jglick** [comment]
For a library wrapper plugin like this, https://github.com/jenkinsci/commons-lang3-api-plugin/blob/8d5a4d30c0840f7d3b1a97a511999c4e2ecd7721/pom.xml#L11-L14 is fragile (you could neglect to change the plugin version after Dependabot bumps the library). https://www.jenkins.io/doc/developer/publishing/releasing-cd/#update-maven-pom-and-config shows a trick to automate this (which could probably also work for an MRP-based plugin if you wanted).

**Comment by timja** [comment]
https://github.com/jenkins-infra/repository-permissions-updater/pull/2659/commits/1be72d9f5ee3beb40dd200cea0130e16ec0a4852
