### ISSUE TITLE
Cycle in plugin dependencies

### ISSUE THREAD

**Issue by kevinleturc** [jenkinsci/commons-lang3-api-plugin#18]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Jenkins is running in a Kubernetes cluster.

### Reproduction steps

Start Jenkins with the plugins below: 
  - blueocean
  - configuration-as-code
  - configuration-as-code-groovy
  - credentials
  - cucumber-reports
  - disable-github-multibranch-status
  - embeddable-build-status
  - extended-read-permission
  - git
  - github
  - github-checks
  - github-oauth
  - jira
  - jira-steps
  - job-dsl
  - kubernetes:1.30.3
  - kubernetes-client-api:5.4.1
  - kubernetes-credentials-provider
  - kubernetes-credentials-provider:0.20
  - lockable-resources
  - matrix-auth
  - pipeline-github
  - pipeline-utility-steps
  - rebuild
  - slack
  - text-finder
  - timestamper
  - workflow-aggregator
  - workflow-job

### Expected Results

Jenkins is able to start.

### Actual Results

Jenkins isn't starting, we observe this message in the logs:
```
SEVERE  hudson.PluginManager$1$3$2$1#reactOnCycle: found cycle in plugin dependencies: (root=Plugin:sshd, deactivating all involved) Plugin:sshd -> Plugin:mina-sshd-api-core -> Plugin:ssh-credential
s -> Plugin:credentials -> Plugin:configuration-as-code -> Plugin:commons-text-api -> Plugin:commons-lang3-api -> Plugin:sshd
```

Followed by various message like the one below:
```
SEVERE  jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Jenkins JSch dependency plugin v0.1.55.2 (jsch)
java.io.IOException: Failed to load: Jenkins JSch dependency plugin (0.1.55.2)
 - Required plugin is disabled: SSH Credentials Plugin
        at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:1016)
        at hudson.PluginManager$2$1$1.run(PluginManager.java:535)
        at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
        at jenkins.model.Jenkins$5.runTask(Jenkins.java:1151)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
        at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

Jenkins is failing to start due to the absence of various plugins.

### Anything else?

I think the issue was introduced by this change in `configuration-as-code` plugin: https://github.com/jenkinsci/configuration-as-code-plugin/pull/1979 which makes `configuration-as-code` plugin dependant of `commons-lang3-api` plugin which depends implicitly on `sshd` plugin probably because the required Jenkins version of `commons-lang3-api` is `2.277.1` whereas `sshd` requires `2.289.1`.

I saw that the required Jenkins version was updated [there](https://github.com/jenkinsci/commons-lang3-api-plugin/commit/23a01815f23b697597018d19c67c8ab7f0c00abf) but hasn't been released yet.

Could the plugin be released if the error is indeed due to this implied dependency?

Thanks

**Comment by Tas-sos** [comment]
Unfortunately, I have exactly the same problem.

* `Jenkins 2.346.2`
```
The following plugins are deactivated because of cyclic dependencies, most likely you can resolve the issue by updating these to a newer version
    Configuration as Code Plugin v1466.v2d4119502006
    SSH Credentials Plugin v291.v8211e4f8efb_c
    commons-lang3 v3.x Jenkins Api Plugin v3.12.0.0
    Credentials Plugin v1139.veb_9579fca_33b_
    Mina SSHD API :: Core v2.8.0-30.vf9df64641cb_d
    SSH server v3.242.va_db_9da_b_26a_c3
    commons-text API Plugin v1.9-9.v39a_53e2e0343
```

**Comment by pjfila** [comment]
Same here, my plugins:
plugins:
  - ansicolor
  - atlassian-bitbucket-server-integration
  - bitbucket
  - blueocean
  - cloudbees-bitbucket-branch-source
  - config-file-provider
  - configuration-as-code
  - copyartifact
  - credentials
  - docker-workflow
  - email-ext
  - envinject
  - extended-choice-parameter
  - file-operations
  - git
  - git-parameter
  - gradle
  - htmlpublisher
  - jdk-tool
  - job-dsl
  - kubernetes
  - nexus-artifact-uploader
  - openshift-client
  - openshift-login
  - parameter-separator
  - pipeline-global-lib-nexus
  - pipeline-utility-steps
  - scriptler
  - simple-theme-plugin
  - slack
  - ssh-slaves
  - swarm
  - workflow-aggregator
  - workflow-basic-steps
  - workflow-multibranch
  - ws-cleanup
  - uno-choice:2.4

**Comment by chaitukr11** [comment]
> Also filed as https://issues.jenkins.io/browse/JENKINS-69034

Thanks, Resolved with workarounds.

**Comment by MichaelBMiner** [comment]
When can we expect these to be merged? This issue is currently blocking my team.

**Comment by Tas-sos** [comment]
My workaround with this wonderful tool https://github.com/jenkinsci/plugin-installation-manager-tool/releases/tag/2.12.8 was to downgrade the `mina-sshd-api-core` from `2.8.0-30.vf9df64641cb_d` back to ==> `2.8.0-21.v493b_6b_db_22c6`

**Comment by jglick** [comment]
> When can we expect these to be merged?

https://github.com/jenkins-infra/repository-permissions-updater/pull/2659 would need to be approved by the current sole maintainer, @nhojpatrick. https://github.com/jenkinsci/configuration-as-code-plugin/pull/1979#issuecomment-1187670236 would also suffice.

**Comment by andreisilviudragnea** [comment]
This bug also affects our team too:

**Comment by jetersen** [comment]
This release of JCasC should solve your cycle dependency issue: https://github.com/jenkinsci/configuration-as-code-plugin/releases/tag/1511.vb_f985b_894e40

@andreisilviudragnea I'd suggest keeping your AWS EC2 cloud configuration in JCasC you should be able to export. Also you should always backup your config even with JCasC.

**Comment by Tas-sos** [comment]
@andreisilviudragnea After all that crap, we also lost all **Configure Clouds** configuration and I've been trying since yesterday to fix our OpenStack connection.... :exploding_head: 
I'm not sure yet, but I fear that maybe something else is also disrupting/prevents proper connection to OpenStack.
From yesterday we running on `Jenkins 2.346.2 LTS`.
I do not know **why** we lost everything from **Configure Clouds**. :disappointed:

**Comment by jetersen** [comment]
A thing we used often was to have a container image for dev and prod. The dev also had access to cloud config using default application credentials from either AWS or Google Cloud.

**Comment by Tas-sos** [comment]
I updated again all plugins and the problem with `cyclic dependencies` seems to go away.
